# Generated by Django 5.2.3 on 2025-06-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
