# Generated by Django 5.2.3 on 2025-06-30 05:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('specialty', models.CharField(choices=[('general', 'Medicina General'), ('cardiology', 'Cardiología'), ('neurology', 'Neurología'), ('pediatrics', 'Pediatría'), ('psychiatry', 'Psiquiatría'), ('orthopedics', 'Traumatología'), ('dermatology', 'Dermatología'), ('gynecology', 'Ginecología')], max_length=50)),
                ('license_number', models.CharField(default='LIC-000000', max_length=20, unique=True, verbose_name='Número de Licencia')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('education', models.TextField(blank=True, verbose_name='Educación')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('medical_history', models.TextField(blank=True, verbose_name='Historia Médica')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name='Contacto de Emergencia')),
                ('priority_level', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.doctor')),
            ],
            options={
                'verbose_name': 'Horario del Doctor',
                'verbose_name_plural': 'Horarios de Doctores',
                'unique_together': {('doctor', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('reason', models.TextField(verbose_name='Motivo de la consulta')),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consulta'), ('follow_up', 'Seguimiento'), ('emergency', 'Emergencia'), ('routine', 'Rutina')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('in-progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no-show', 'No se presentó'), ('rescheduled', 'Reprogramada')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True, verbose_name='Notas del doctor')),
                ('patient_notes', models.TextField(blank=True, verbose_name='Notas del paciente')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('treatment', models.TextField(blank=True, verbose_name='Tratamiento')),
                ('prescription', models.TextField(blank=True, verbose_name='Prescripción')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('guestId', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['-date', '-time'],
                'unique_together': {('doctor', 'date', 'time')},
            },
        ),
    ]
