# Generated by Django 5.2.3 on 2025-06-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Licencia'),
        ),
    ]
